### ISSUE TITLE
Galaxy Buds Original support?

### ISSUE THREAD

**Issue by marvic2409** [JojiiOfficial/LiveBudsCli#10]
I was wondering if it was possible to add support for the original galaxy buds?

**Comment by JojiiOfficial** [comment]
Theoretically its possible and shouldn't be that hard to implement. Since I only own the Buds live, I can't add it without testing it properly.

**Comment by marvic2409** [comment]
What would you have to change? (Not very familiar with rust but I do have galaxy buds and can use a computer)

**Comment by JojiiOfficial** [comment]
You'd basically need to create a lib like the [GalaxyBudsLive-rs](https://github.com/JojiiOfficial/GalaxyBudsLive-rs) but for the buds or buds+. You can have a look into [this](https://github.com/ThePBone/GalaxyBudsClient/blob/master/Galaxy%20Buds%20Plus%20RFComm%20Protocol%20Notes.md) and [this](https://github.com/ThePBone/GalaxyBudsClient/blob/master/GalaxyBudsRFCommProtocol.md) if you don't want to debug it yourself. The features needed to be implemented by this tool are:

### Decoding
- ExtendedStatusUpdate
- StatusUpdate

### Encoding
- Simple
- LockTouchpad
- SetNoiseReduction
- SetTouchpadOption

If you get to create such a library which is working with your buds, I'll implement the rest to make it work with this tool. Refer to the [examples](https://github.com/JojiiOfficial/GalaxyBudsLive-rs/tree/master/examples) of the GalaxyBudsLive-rs crate if you want to.

**Comment by JojiiOfficial** [comment]
I just got told that they already do work for the Galaxy Buds+. Can anyone test this and give me feedback for potential bugs?

**Comment by JojiiOfficial** [comment]
This feature is planned. Therefore I added it as TODO to #29. Therefore I'll close this issue.
