### ISSUE TITLE
Properly Implement support for Buds+

### ISSUE THREAD

**Issue by JojiiOfficial** [JojiiOfficial/LiveBudsCli#23]
Some values seem to be parsed wrongly for the Buds+. 

Wrongly parsed values:
 
- [x] Temparature (MsgDebugGetAllData)
- [x] Touchpad options (MsgExtendedStatusUpdate)
- [x] Ambient mode

**Comment by JojiiOfficial** [comment]
Can someone with Buds+ test out all functions and its state of working? The functions to test would be all set commands with each all possible values and verifying each command with `earbuds status`s output to match the changed value.

**Comment by sam5558** [comment]
Hi again,

I've tried the `earbuds set equalizer` command. 
I'm able to switch from normal to bassboost on buds+.
```
$ ./target/release/earbuds status
Info for 'Galaxy Buds+ (7808)':

Battery:	L: 99%, R: 86%
Case:		72%
Equalizer:	Normal
ANC:		Enabled
Touchpads:	Enabled
Left option:	Undetected
Right option:	Volume
Temp. left:	0.0°C
Temp. right:	0.0°C
```
```
$ ./target/release/earbuds set equalizer bass
Custom { kind: InvalidData, error: "stream did not contain valid UTF-8" }
```
```
$ ./target/release/earbuds status
Info for 'Galaxy Buds+ (7808)':

Battery:	L: 99%, R: 86%
Case:		72%
Equalizer:	BassBoost
ANC:		Enabled
Touchpads:	Enabled
Left option:	Undetected
Right option:	Volume
Temp. left:	0.0°C
Temp. right:	0.0°C
```

Not sure what are the other commands you want to test.
Just give me what other commands you want to test.

**Comment by JojiiOfficial** [comment]
This error doesn't seem to be right... I'll look up what kind of invalid data is returned by the daemon. Could you try out following commands and check it each time with `earbuds status`?

- tap-action (volume, spotify, anc)
- touchpadlock (on/off)
- anc (on/off)

**Comment by sam5558** [comment]
enabled anc & touchpad : 
```
Info for 'Galaxy Buds+ (7808)':

Battery:	L: 99%, R: 86%
Case:		72%
Equalizer:	BassBoost
ANC:		Enabled
Touchpads:	Enabled
Left option:	Undetected
Right option:	Volume
Temp. left:	0.0°C
Temp. right:	0.0°C
```
disabled anc & blocked touchpad : 
```
Info for 'Galaxy Buds+ (7808)':

Battery:	L: 99%, R: 86%
Case:		72%
Equalizer:	BassBoost
ANC:		Disabled
Touchpads:	Blocked
Left option:	Undetected
Right option:	Volume
Temp. left:	0.0°C
Temp. right:	0.0°C
```
earbuds set tap-action spotify left
```
Info for 'Galaxy Buds+ (7808)':

Battery:	L: 99%, R: 86%
Case:		72%
Equalizer:	BassBoost
ANC:		Enabled
Touchpads:	Blocked
Left option:	Spotify
Right option:	Volume
Temp. left:	0.0°C
Temp. right:	0.0°C
```
=> Holding the left button doesn't seem to launch spotify (i do have spotify installed)
=> Holding right button doesn't seem to change volume either up or down...

Sorry for that, maybe someone else that has buds+ and linux should try the same commands.

**Comment by JojiiOfficial** [comment]
Thank you. Does the error from your previous comment show up on every `set` command?
I don't think someone else will encounter a different output but it wouldn't be pointless to try it out.

> Holding the left button doesn't seem to launch spotify (i do have spotify installed)
Spotify isn't supposed to launch/work (yet). The option is just available for integrity.

Thank you for your help! I'm gonna look into it soon and hope I'll find out what exactly the problem is

**Comment by sam5558** [comment]
> Does the error from your previous comment show up on every set command?

If you mean this output : `Custom { kind: InvalidData, error: "stream did not contain valid UTF-8" }` then yes, each time i execute a command that changes the value of any field it does show me this message.

**Comment by JojiiOfficial** [comment]
Interesting error though...

Could you run `earbuds -dk --no-fork` in a separate terminal, wait 3s and run `earbuds status -v -o json | jq` in another terminal, while wearing only one of them? Please paste the output (with omitted 'address' and 'device' fields).

**Comment by sam5558** [comment]
Hi,

`$ ./target/release/earbuds -dk --no-fork`
```
Connected successfully to Buds live!
thread 'async-std/runtime' panicked at 'index out of bounds: the len is 87 but the index is 87', /home/zen/.cargo/registry/src/github.com-1ecc6299db9ec823/galaxy_buds_live_rs-0.2.0/src/utils/byteutil.rs:18:7
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
`$ ./target/release/earbuds status -v -o json | jq` (Using just right earbud+)
```
{
  "status": "success",
  "device": ".....",
  "status_message": null,
  "payload": {
    "address": ".....",
    "ready": true,
    "batt_left": 0,
    "batt_right": 100,
    "batt_case": 26,
    "placement_left": 0,
    "placement_right": 1,
    "equalizer_type": 0,
    "touchpads_blocked": false,
    "noise_reduction": false,
    "did_battery_notify": false,
    "touchpad_option_left": 0,
    "touchpad_option_right": 3,
    "paused_music_earlier": false,
    "debug": {
      "voltage_left": 0,
      "voltage_right": 0,
      "temperature_left": 0,
      "temperature_right": 0,
      "current_left": 0,
      "current_right": 0
    }
  }
}
```

**Comment by JojiiOfficial** [comment]
Thanks! This output & error helps a lot.

**Comment by JojiiOfficial** [comment]
I've created a [new branch](https://github.com/JojiiOfficial/LiveBudsCli/tree/official_buds_support) to add buds support officially. The panic from your last output and the wrongly displayed status should be fixed with this. To test it:
```bash
git clone https://github.com/JojiiOfficial/LiveBudsCli
git checkout official_buds_support
```
and then the `cargo build` command you used before.

**Comment by sam5558** [comment]
It's working !! Thank you for that.

```
Daemon started successfully
Info for 'Galaxy Buds+ (7808)':

Battery:	L: 95%, R: 93%
Equalizer:	Dynamic
ANC:		Disabled
Touchpads:	Enabled
Left option:	Volume
Right option:	Volume
Temp. left:	33.9°C
Temp. right:	32.8°C
```

**Comment by JojiiOfficial** [comment]
I have to thank you for testing it that frequently. One more thing though...
Is the `Custom { kind: InvalidData, error: "stream did not contain valid UTF-8" }` error still persistent?
And do you experience some other inconveniences like errors, invalidly displayed values or things you don't feel comfortable to use they way they are?

**Comment by sam5558** [comment]
Hello,
I now get a "success" output instead of the weird `Custom { kind: InvalidData, error: "stream did not contain valid UTF-8" }`.. meaning it should be okay :)
```
$ earbuds status -v
Info for 'Galaxy Buds+ (7808)':

Type:		BudsPlus
Battery:	L: 0%, R: 100%
Equalizer:	Dynamic
ANC:		Disabled
Touchpads:	Enabled
Left option:	Volume
Right option:	Volume
Temp. left:	0.0°C
Temp. right:	17.4°C
Current left:	0.0mA
Current right:	25.0mA
Volt left:	0.0V
Volt right:	4.0V
```
```
$ earbuds set equalizer bass
Success
```
```
$ earbuds status -v
Info for 'Galaxy Buds+ (7808)':

Type:		BudsPlus
Battery:	L: 0%, R: 100%
Equalizer:	BassBoost
ANC:		Disabled
Touchpads:	Enabled
Left option:	Volume
Right option:	Volume
Temp. left:	0.0°C
Temp. right:	17.9°C
Current left:	0.0mA
Current right:	30.0mA
Volt left:	0.0V
Volt right:	4.0V
```

**Comment by JojiiOfficial** [comment]
However your left earbud seems not to work properly. Is it connected?

**Comment by sam5558** [comment]
It wasn't connected. Here's the output with both of them : 
```
Info for 'Galaxy Buds+ (7808)':

Type:		BudsPlus
Battery:	L: 100%, R: 92%
Equalizer:	BassBoost
ANC:		Disabled
Touchpads:	Enabled
Left option:	Volume
Right option:	Volume
Temp. left:	15.0°C
Temp. right:	33.1°C
Current left:	52.0mA
Current right:	59.0mA
Volt left:	4.06V
Volt right:	3.97V
```

**Comment by JojiiOfficial** [comment]
Good no hear that. There is still a difference between the buds live and buds+ when it comes to anc. I'll implement ambient sound options for buds+ and if that works, I'll draft the new release.

**Comment by sam5558** [comment]
I see.
Thank you for your reactivity !

**Comment by JojiiOfficial** [comment]
Thank you for testing :)

I just created a prototype of an ambient sound implementation. If you want to, have a look at [this branch](https://github.com/JojiiOfficial/LiveBudsCli/tree/add_ambient_volume) and try it out. The following subcommand was added:

`earbuds set ambientsound <0-4>`

0: off
1-4: ambient volume levels.

Start the deamon in a separate terminal like you [did here](https://github.com/JojiiOfficial/LiveBudsCli/issues/23#issuecomment-751715635).
Try to break it, so play around with the number as much as you want. Errors often help more. If you encounter errors (eg. the ambient volume doesn't change even though you ran the command) please also paste the output of the daemon from the other terminal.
