### ISSUE TITLE
error[E0308]: mismatched types

### ISSUE THREAD

**Issue by linuxaficionado** [JojiiOfficial/LiveBudsCli#24]
Compiling earbuds using cargo errors out when running cargo install earbuds.

Compiling errors on compiling rust-pulsectl v0.2.6.

Using Ubuntu 20.10 to compile.

I have attached two files containing the error output from cargo install earbuds and cargo install earbuds --verbose.

[standard output.txt](https://github.com/JojiiOfficial/LiveBudsCli/files/5746769/standard.output.txt)
[verbose output.txt](https://github.com/JojiiOfficial/LiveBudsCli/files/5746770/verbose.output.txt)

Not to sure what information you require.

**Comment by JojiiOfficial** [comment]
This error has already been fixed. Use the latest git version.
