### ISSUE TITLE
Polybar script doesn't work

### ISSUE THREAD

**Issue by glsmith86** [JojiiOfficial/LiveBudsCli#44]
Hello!

I have installed the Polybar on my Ubuntu 20.04.
The polybar.sh script not work.
At the first time say: /bin/sh: 1: /home/glsmith/.config/polybar/scripts/polybar.sh: Permission denied
chmod +x solve this problem.

Second time start problem:
/home/glsmith/.config/polybar/scripts/polybar.sh: 5: [: error: unexpected operator

I can't solve this issue.

**Comment by JojiiOfficial** [comment]
Which shell are you using? You can use `echo $SHELL` to determine the type of shell you're using.

**Comment by glsmith86** [comment]
I change the first line from: #!/bin/sh to: #!/usr/bin/env bash
It's work. Computer shell is /bin/bash.

**Comment by JojiiOfficial** [comment]
Maybe your shell is linked to /bin/dash or your PATH is not properly set inside the script. But changing the scripts shebang to `#!/usr/bin/env bash` isn't a bad idea.
