### ISSUE TITLE
Digital artifacts on audio when daemon is running - Galaxy Buds Live

### ISSUE THREAD

**Issue by matgas23** [JojiiOfficial/LiveBudsCli#50]
Hi! Thank you for this fantastic project. 
However while running the daemon I notice a lot of artifacts on audio. (every 4-5 seconds)
Initially I was thinking of a bluetooth problem but I noticed that by blocking the daemon everything goes back to normal...
Everything seems to be recognized correctly by observing the output of the command "earbuds status -v":

```
$ earbuds status -v
Info for 'Galaxy Buds Live (452C)':

Type:		BudsLive
Battery:	L: 91%, R: 77%
Equalizer:	Normal
ANC:		Enabled
Touchpads:	Enabled
Left option:	NoiseCanceling
Right option:	VoiceCommand
Temp. left:	36.9°C
Temp. right:	36.7°C
Current left:	70.0mA
Current right:	61.0mA
Volt left:	4.02V
Volt right:	3.89V
```

**Comment by JojiiOfficial** [comment]
Is the firmware of your buds updated to the latest version?

**Comment by matgas23** [comment]
1- Yes. I just checked on GalaxyWear app: R180XXU0ATK2
2- Yes, I'm killing it with "earbuds -k"

**Comment by JojiiOfficial** [comment]
Which audio server, distro and LiveBudsCli version are you using?
From where did you install it?

**Comment by matgas23** [comment]
I restarted the PC just now and it seems to work. Probably as you said there was too much RFCOMM connections opened...
Tomorrow I'll have a chance to test the system properly.
Matteo

**Comment by JojiiOfficial** [comment]
Closing due inactivity. Reopen if the issue still exists.
