### ISSUE TITLE
Fish shell completions not working

### ISSUE THREAD

**Issue by Diaoul** [JojiiOfficial/LiveBudsCli#58]
Starting to type `earbuds` gives this error with fish:
```
/usr/share/fish/vendor_completions.d/earbuds.fish (line 12): Unexpected ')' found, expecting '}'
            earbuds)
                   ^
from sourcing file /usr/share/fish/vendor_completions.d/earbuds.fish
in command substitution
source: Error while reading file “/usr/share/fish/vendor_completions.d/earbuds.fish”
```

Running up-to-date Arch Linux.

Awesome work btw! can't wait to get my polybar setup with this :+1:

**Comment by JojiiOfficial** [comment]
`./target/release/${pkgname} --generate=bash > ${pkgname}.fish`
Looks like the PKGBUILD is generating bash completion for fish shell completion... I'll create a new version and upload it to the AUR.

**Comment by JojiiOfficial** [comment]
The new version is available. Please reopen this issue if the error still persists.
