### ISSUE TITLE
Case Battery Level 

### ISSUE THREAD

**Issue by KonstantMan** [JojiiOfficial/LiveBudsCli#62]
It's not really that your app lacks any features you have done an amazing job and for me at least it doesn't have any bugs, The only thing I miss is the ability to see the battery level of the case too

**Comment by JojiiOfficial** [comment]
The case battery level can only reliably be shown if at least one bud is connected to the case. I could store the last battery level and update it if a bud connects to the case but then the case battery level isn't always 100% correct.

**Comment by KonstantMan** [comment]
So is there the ability to show the case Battery when i have at least one bud in the case and run earbuds status?

**Comment by JojiiOfficial** [comment]
Yes
